modLoader = "kotlinforforge"
loaderVersion = "[4.10,)"
#issueTrackerURL = ""
license = "Insert License Here"

[[mods]]
modId = "aris"
version = "${version}"
displayName = "Project Aris"
authors = "Dayo"
description = '''
Project Aris
'''
#logoFile = ""

[[dependencies.aris]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.aris]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"
